# Generated by Django 3.1.7 on 2021-03-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvshows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TvShowPeople",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person_id", models.IntegerField(blank=True, null=True)),
                ("tv_show_id", models.IntegerField(blank=True, null=True)),
                (
                    "person_role",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("order", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Tv Show Person",
                "verbose_name_plural": "Tv Show People",
                "db_table": "tv_show_people",
                "managed": False,
            },
        ),
    ]
