# Generated by Django 3.1.7 on 2021-04-20 11:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvshows", "0002_tvshowpeople"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seasons",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                ("tv_show_id", models.IntegerField(blank=True, null=True)),
                ("air_date", models.DateField(blank=True, null=True)),
                ("season_number", models.IntegerField(blank=True, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("poster_file_size", models.IntegerField(blank=True, null=True)),
                ("poster_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "db_table": "seasons",
                "managed": False,
            },
        ),
    ]
