# Generated by Django 3.1.7 on 2021-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvshows", "0005_tvshowtranslationaliases"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episodes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("tv_show_id", models.IntegerField(blank=True, null=True)),
                ("season_id", models.IntegerField(blank=True, null=True)),
                ("season_number", models.IntegerField(blank=True, null=True)),
                ("air_date", models.DateField(blank=True, null=True)),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                ("episode_number", models.IntegerField(blank=True, null=True)),
                ("imdb_id", models.CharField(blank=True, max_length=255, null=True)),
                ("imdb_rating", models.FloatField(blank=True, null=True)),
                ("photo_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo_file_size", models.IntegerField(blank=True, null=True)),
                ("photo_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Episode",
                "verbose_name_plural": "Episodes",
                "db_table": "episodes",
                "managed": False,
            },
        ),
    ]
