# Generated by Django 3.1.7 on 2021-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tvshows", "0006_episodes"),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeTranslations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("locale", models.CharField(blank=True, max_length=255, null=True)),
                ("episode_id", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Episode Translation",
                "verbose_name_plural": "Episodes Translations",
                "db_table": "episode_translations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeasonTranslations",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_id", models.IntegerField(blank=True, null=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("locale", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("poster_file_size", models.IntegerField(blank=True, null=True)),
                ("poster_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Season Translation",
                "verbose_name_plural": "Seasons Translations",
                "db_table": "season_translations",
                "managed": False,
            },
        ),
    ]
