# Generated by Django 3.2.13 on 2022-09-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinemas', '0013_alter_cinemas_options'),
    ]

    operations = [
        
    ]
