# Generated by Django 3.2.13 on 2022-09-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_appusers_errors_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errors',
            name='alert',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='errors',
            name='error',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='errors',
            name='warning',
            field=models.TextField(null=True),
        ),
    ]
