# Generated by Django 3.1.7 on 2021-03-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Distributors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_id", models.CharField(blank=True, max_length=255, null=True)),
                ("locale", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Distributor",
                "verbose_name_plural": "Distributors",
                "db_table": "distributors",
                "managed": False,
            },
        ),
    ]
