# Generated by Django 3.1.7 on 2021-03-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="MoviesServices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.IntegerField(blank=True, null=True)),
                ("movie_id", models.IntegerField(blank=True, null=True)),
                ("info_id", models.IntegerField(blank=True, null=True)),
                ("locale", models.CharField(blank=True, max_length=255, null=True)),
                ("rent_price", models.FloatField(blank=True, null=True)),
                ("buy_price", models.FloatField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("flat", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("prices", models.TextField(blank=True, null=True)),
                (
                    "update_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "service_movie_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Movie Service",
                "verbose_name_plural": "Movies Services",
                "db_table": "movies_services",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SeasonServices",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tv_show_translation_id", models.IntegerField(blank=True, null=True)),
                ("tv_show_id", models.IntegerField(blank=True, null=True)),
                ("service_id", models.IntegerField(blank=True, null=True)),
                (
                    "service_season_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("season_id", models.IntegerField(blank=True, null=True)),
                ("season_translation_id", models.IntegerField(blank=True, null=True)),
                ("locale", models.CharField(blank=True, max_length=255, null=True)),
                ("rent_price", models.FloatField(blank=True, null=True)),
                ("buy_price", models.FloatField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("flat", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("season_number", models.IntegerField(blank=True, null=True)),
                ("buy_episodes", models.IntegerField(blank=True, null=True)),
                ("prices", models.TextField(blank=True, null=True)),
                (
                    "update_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "service_tv_show_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "verbose_name": "Season Service",
                "verbose_name_plural": "Season Services",
                "db_table": "season_services",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("web", models.CharField(blank=True, max_length=255, null=True)),
                ("tos", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("active", models.IntegerField(blank=True, null=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("priority", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
                "db_table": "services",
                "managed": False,
            },
        ),
    ]
