# Generated by Django 3.1.7 on 2021-03-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Charts",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("locale", models.CharField(blank=True, max_length=255, null=True)),
                ("info_id", models.IntegerField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("previous", models.IntegerField(blank=True, null=True)),
                ("week_seats", models.IntegerField(blank=True, null=True)),
                ("total_seats", models.IntegerField(blank=True, null=True)),
                ("week_revenue", models.IntegerField(blank=True, null=True)),
                ("total_revenue", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("from_date", models.DateTimeField(blank=True, null=True)),
                ("to_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chart",
                "verbose_name_plural": "Charts",
                "db_table": "charts",
                "managed": False,
            },
        ),
    ]
