# Generated by Django 3.1.7 on 2021-03-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinemas", "0002_showtimes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parsers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cinema_id", models.IntegerField(blank=True, null=True)),
                (
                    "rss_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateTimeField(blank=True, null=True)),
                ("last_log", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "parser_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("priority", models.IntegerField(blank=True, null=True)),
                ("night_queue", models.IntegerField(blank=True, null=True)),
                ("in_app_booking", models.IntegerField(blank=True, null=True)),
                ("hour_queue", models.IntegerField(blank=True, null=True)),
                ("custom_attributes", models.TextField(blank=True, null=True)),
                ("queue", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Parser",
                "verbose_name_plural": "Parsers",
                "db_table": "parsers",
                "managed": False,
            },
        ),
    ]
