# Generated by Django 3.2.13 on 2022-08-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        # ('movies', '0007_auto_20220803_1106'),
        ('cinemas', '0004_kinoheld'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kinoheld',
        ),
        migrations.CreateModel(
            name='MoviePlaylist',
            fields=[
            ],
            options={
                'verbose_name': 'Movie in Playlist',
                'verbose_name_plural': 'Movies in Playlist',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('movies.infos',),
        ),
        migrations.CreateModel(
            name='NewKinoheldCinemas',
            fields=[
            ],
            options={
                'verbose_name': 'New Kinoheld Cinema',
                'verbose_name_plural': 'New Kinoheld Cinemas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cinemas.cinemas',),
        ),
        migrations.CreateModel(
            name='RemovedKinoheldCinemas',
            fields=[
            ],
            options={
                'verbose_name': 'Removed Kinoheld Cinema',
                'verbose_name_plural': 'Removed Kinoheld Cinemas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cinemas.cinemas',),
        ),
        migrations.AlterModelOptions(
            name='cinemas',
            options={'verbose_name': 'Cinema', 'verbose_name_plural': 'Cinemas'},
        ),
    ]
