# Generated by Django 3.2.13 on 2022-08-10 07:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0005_auto_20220810_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemas',
            name='chain_id',
        ),
        migrations.RemoveField(
            model_name='cinemas',
            name='setting_group_id',
        ),
        migrations.AddField(
            model_name='cinemas',
            name='chain',
            field=models.ForeignKey(db_column='chain_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='cinemas.chains'),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='cinema_type',
            field=models.CharField(blank=True, choices=[('cinema', 'cinema'), ('occasional', 'occasional'), ('open-air', 'open-air'), ('mobile', 'mobile'), ('', '')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cinemas',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
