# Generated by Django 3.2.13 on 2022-08-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0006_auto_20220810_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemas',
            name='setting_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
