# Generated by Django 3.2.13 on 2022-08-10 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0007_cinemas_setting_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinemas',
            name='setting_group_id',
        ),
    ]
