# Generated by Django 3.2.13 on 2022-08-10 07:35

from django.db import migrations
from cinemas.models import Chains, Cinemas

def add_chain_ids(*args):
    chains = Chains.objects.all()
    for chain in chains:

        cinemas = Cinemas.objects.filter(name__icontains = chain.name, locale = chain.locale).update(chain = chain, buffer = 20)


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0010_auto_20220810_0714'),
    ]

    operations = [
        migrations.RunPython(add_chain_ids),
    ]
