# Generated by Django 3.2.13 on 2022-08-18 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinemas', '0012_auto_20220810_0746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cinemas',
            options={'managed': False, 'verbose_name': 'Cinema', 'verbose_name_plural': 'Cinemas'},
        ),
    ]
