# Generated by Django 3.1.7 on 2021-04-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Spotlights",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "spotlight_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("position", models.IntegerField(blank=True, null=True)),
                ("available_from", models.DateTimeField(blank=True, null=True)),
                ("available_until", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "background_56_portrait_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "background_56_portrait_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "background_56_portrait_file_size",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "background_56_portrait_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "video_56_portrait_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "video_56_portrait_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "video_56_portrait_file_size",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "video_56_portrait_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "background_75_portrait_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "background_75_portrait_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "background_75_portrait_file_size",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "background_75_portrait_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "background_75_landscape_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "background_75_landscape_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "background_75_landscape_file_size",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "background_75_landscape_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                (
                    "target_link",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo_file_size", models.IntegerField(blank=True, null=True)),
                ("photo_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Spotlight",
                "verbose_name_plural": "Spotlights",
                "db_table": "spotlights",
                "managed": False,
            },
        ),
    ]
