# Generated by Django 3.1.7 on 2021-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Lists",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("layout", models.CharField(blank=True, max_length=255, null=True)),
                ("active", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("de_name", models.CharField(blank=True, max_length=255, null=True)),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("lt_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "List",
                "verbose_name_plural": "Lists",
                "db_table": "lists",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ListsMovies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(blank=True, null=True)),
                ("list_id", models.IntegerField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Lists Movie",
                "verbose_name_plural": "Lists Movies",
                "db_table": "lists_movies",
                "managed": False,
            },
        ),
    ]
