# Generated by Django 3.1.7 on 2021-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                (
                    "poster_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "poster_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("poster_file_size", models.IntegerField(blank=True, null=True)),
                ("poster_updated_at", models.DateTimeField(blank=True, null=True)),
                ("ignore", models.IntegerField(blank=True, null=True)),
                ("imdb_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo_file_size", models.IntegerField(blank=True, null=True)),
                ("photo_updated_at", models.DateTimeField(blank=True, null=True)),
                ("rss_title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "premiere_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("imdb_rating", models.FloatField(blank=True, null=True)),
                ("tomato_rating", models.FloatField(blank=True, null=True)),
                ("stars_average", models.FloatField(blank=True, null=True)),
                ("stars_count", models.IntegerField(blank=True, null=True)),
                ("watchlist_count", models.IntegerField(blank=True, null=True)),
                ("genre", models.CharField(blank=True, max_length=255, null=True)),
                ("tomato_id", models.CharField(blank=True, max_length=255, null=True)),
                ("metacritic_rating", models.FloatField(blank=True, null=True)),
                (
                    "metacritic_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "motion_poster_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "motion_poster_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("motion_poster_file_size", models.IntegerField(blank=True, null=True)),
                (
                    "motion_poster_updated_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("poster_parser_count", models.IntegerField(blank=True, null=True)),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                ("tmdb_popularity", models.FloatField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("budget", models.FloatField(blank=True, null=True)),
                ("revenue", models.FloatField(blank=True, null=True)),
                (
                    "spoken_languages",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("made_in", models.CharField(blank=True, max_length=255, null=True)),
                ("paths_to_posters", models.TextField(blank=True, null=True)),
                (
                    "original_language",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paths_to_photos", models.TextField(blank=True, null=True)),
                ("locked_attributes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "movies",
                "managed": False,
            },
        ),
    ]
