# Generated by Django 3.1.7 on 2021-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_auto_20210326_1831"),
    ]

    operations = [
        migrations.CreateModel(
            name="People",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(blank=True, null=True)),
                ("imdb_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "also_known_as",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("biography", models.TextField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("deathday", models.DateField(blank=True, null=True)),
                ("homepage", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("popularity", models.FloatField(blank=True, null=True)),
                ("photo_path", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "photo_file_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "photo_content_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("photo_file_size", models.IntegerField(blank=True, null=True)),
                ("photo_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("paths_to_photos", models.TextField(blank=True, null=True)),
                ("show_images", models.IntegerField(blank=True, null=True)),
                ("locked_attributes", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Person",
                "verbose_name_plural": "People",
                "db_table": "people",
                "managed": False,
            },
        ),
    ]
