# Generated by Django 3.1.7 on 2021-04-26 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_moviespeople"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieAliases",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie_id", models.IntegerField(blank=True, null=True)),
                (
                    "original_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Movie Alias",
                "verbose_name_plural": "Movies Aliases",
                "db_table": "movie_aliases",
                "managed": False,
            },
        ),
    ]
