# Generated by Django 3.1.7 on 2021-05-18 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_moviealiases"),
    ]

    operations = [
        migrations.CreateModel(
            name="InfoAliases",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "locale",
                    models.CharField(default="de", editable=False, max_length=10),
                ),
            ],
            options={
                "verbose_name": "Info Alias",
                "verbose_name_plural": "Infos Aliases",
                "db_table": "info_aliases",
                "managed": False,
            },
        ),
    ]
